language: rust
rust:
  - stable
services:
  - docker
dist: xenial
sudo: required
env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pip install --user awscli
  - pip install --user aws-sam-cli

script: make deploy