[package]
name = "telegram-bot"
version = "0.1.0"
authors = ["Dawson Israel <dawfre@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
